apiVersion: v2
name: inferencepool
description: A Helm chart for InferencePool

type: application

version: 0.0.0

appVersion: "0.0.0"

dependencies:
  - name: epp
    # This must match the version inside epp/Chart.yaml exactly
    version: 0.1.0
    # Use file:// protocol with relative path to the sibling
    repository: "file://../epp"
